#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/with-ours/platform-sdk-go,github.com/stainless-sdks/ours-privacy-platform-go"

REPLACEMENT="${1:-"../ours-privacy-platform-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/with-ours/platform-sdk-go="$REPLACEMENT"
go mod tidy -e
